project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Renewable Energy"
  author:
    - Sharon Tsai (ct3263)
    - Renee Hsiao (jh4947) 
    - Jose Murguia Fuentes (jm5890)
  repo-url: https://github.com/JoseMF95/renewable_energy
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


